### ISSUE TITLE
Get rid of events

### ISSUE THREAD

**Issue by jirihelmich** [MewsSystems/fiscalization-czechia#12]
It can cause troubles when combined with async calls.

**Comment by mcduke** [comment]
Will there be an alternative way of getting at the serialized XML message?

**Comment by jirihelmich** [comment]
Sure. We were just talking to extend the result object with some property like Details or Statistics that would provide everything that is currently available to be captured using the events. And more.

**Comment by mcduke** [comment]
That sounds great. Access to the raw response XML would be really useful for logging purposes, in addition to the serialized (outgoing) XML message, which would be great to have access to both in case of success and error.

**Comment by jirihelmich** [comment]
Yes, that's something we can do with this. Nice suggestion. Thanks.

**Comment by KaliCZ** [comment]
We will actually change the flow of the library so that the library prepares the request for the user and then the user sends the request, handles connection. Then sends the response content to the library so that it gets parsed. 

Not sure when though. Follow the [new repo](https://github.com/MewsSystems/fiscalizations) if you're interested.
