### ISSUE TITLE
More advanced sample or better documentation

### ISSUE THREAD

**Issue by michalkovy** [MewsSystems/fiscalization-czechia#19]
Please add more advanced sample ideally with all fields. It took me some time searching in source code to find how to use the API, even basic things like getting PKP and BKP, the documentation talks about such fields but they are named differently in source code. Thanks.

**Comment by jirihelmich** [comment]
Sure, I would have done it for you if you would have dropped me a message. I will provide "mapping" to the data items described by etrzby.cz, would that be OK?

**Comment by michalkovy** [comment]
Great, thanks and thanks for the eet implementation, works well.

**Comment by KaliCZ** [comment]
Hey, there has been some iterations since this was created. There's a whole [new repository](https://github.com/MewsSystems/fiscalizations/issues). with automated tests which hopefully do a better job of explaining how it should be used. If not, let's reopen the issue in the new repository. 

Provided the government doesn't cancel EET like they claim they will 😄
